version: '3'
services:
  uri-forwarding-db:
    build: https://github.com/lodqa/uri-forwarding-db.git

  lodqa:
    build: .
    ports:
      - 80:9292
    volumes:
      - .:/app
    environment:
      - URL_FORWARDING_DB=http://uri-forwarding-db:3000
    env_file:
      - sendgrid.env
    depends_on:
      - uri-forwarding-db
